### ISSUE TITLE
ModuleNotFoundError: No module named 'webdriver_manager' 

### ISSUE THREAD

**Issue by mrjng** [kminito/srt_reservation#2]
안녕하세요. SRT 매크로 정말 잘 쓰고 있습니다.

본 repository에 작성된 README.md를 따라 최초 설치 시 본 제목과 같은 에러가 발생합니다.
이 후 `webdriver_manager`를 별도 설치한 후에는 정상 작동됩니다.
해당 모듈을 requirements.txt에 추가해야 할 것으로 보이는데 확인 부탁드립니다.

제가 테스트한 환경은 conda이며, python 3.7 버전으로 진행하였고 다음과 같이 env 생성 후 진행하였습니다.
`conda create -n srt python=3.7`

**Comment by kminito** [comment]
알려주셔서 감사합니다. 조치하겠습니다.
